# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e3f5efaa9db2813a6e3f01ad8f2fa4fb05b32079a35a10628561071bb8e74eb7b5a031c47ca2fbbe5e9512f21086d703067f7377a629882a28d63774804998f

test:
  secret_key_base: 2ac236aed58417a38c3ebb25c65c2927b423dfaf72851376bdd31eb14b43dc0af8e797e42253fb29b3c2bc0f6edb00717ffbbb7f37ba3c1c6135298411a6064c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
